name: send-trigger

on:
  push:
    branches:
      - dev

env:
  ACTIONS_STEP_DEBUG: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: octokit/request-action@v2.x
        id: send-trigger-to-automation-repo
        with:
          route: POST /repos/:repository/actions/workflows/:workflow_id/dispatches
          repository: andycmaj/actions-isolation-automation
          mediaType: | # The | is significant!
            previews: 
              - antiope
          workflow_id: deploy
          ref: $GITHUB_REF
        env:
          GITHUB_TOKEN: 63b62dd0fe5a8cf0659453aa5d7747f046e3a923
