name: send-trigger

on:
  push:
    branches:
      - dev
      - test

env:
  ACTIONS_STEP_DEBUG: true
  WORKFLOW_ID: 2631041

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # outer "ref" is the ref on the automation branch to run the workflow from
      # inner "inputs.ref" is the ref on THIS repo to check out 
      - name: send trigger
        run: |
          curl \
            -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.DISPATCH_TOKEN }}" \
            https://api.github.com/repos/andycmaj/actions-isolation-automation/actions/workflows/$WORKFLOW_ID/dispatches \
            -d '{"ref":"dev","inputs":{"ref":"${GITHUB_REF}"}}'

